aspirateur/tests/amendements/test_fetch_an.py, aspirateur/tests/amendements/test_parse.py, aspirateur/tests/sample_data/dossier-DLR5L15N36030.json, aspirateur/tests/sample_data/dossier-DLR5L15N36159.json, aspirateur/tests/textes/test_get_dossiers_legislatifs.py, aspirateur/zam_aspirateur/amendements/fetch_an.py, aspirateur/zam_aspirateur/amendements/models.py, aspirateur/zam_aspirateur/amendements/parser.py, aspirateur/zam_aspirateur/textes/dossiers_legislatifs.py, aspirateur/zam_aspirateur/textes/models.py, repondeur/tests/test_lectures_add.py, repondeur/zam_repondeur/views/lectures.py, repondeur/zam_repondeur/views/reponse.py
Dans le formulaire d’ajout d’une lecture, on a maintenant la liste des séances publiques + commissions saisies au fond.
Les numéros de texte pour les séances publiques sont maintenant les bons, donc on peut récupérer les amendements.
Par contre la récupération des amendements pour les commissions ne marche pas, et je ne sais pas encore pourquoi (404 → urls différentes pour les récupérer?)
=> Ajout des examens de textes en commission

admin/fabfile.py
- Add option to wipe the DB when deploying the répondeur (the current DB will be backed up to `/var/backups/zam/` first)
- Pin the pipenv version on the server to avoid possible inconsistent behaviours
=> Deployment

repondeur/tests/test_articles_add.py, repondeur/tests/test_fetch.py, repondeur/zam_repondeur/fetch.py
If the case of the Assemblée nationale, the text we want to get the articles of might be:
- the text as initially submitted
- the text as modified by a commission
The URL patterns re different, and the correct one does not depend on whether the lecture is in a commission or in a "séance publique", but on what happened before, and unfortunately we don't keep that information handy.
So the easy way is to just try both URLs in turn, and see which one works...
=> Fix fetching articles content for Assemblée nationale

repondeur/tests/models/test_amendement.py, repondeur/zam_repondeur/models/amendement.py
We only handled the "COM-" prefix, but it looks like others can be used, so we'll just ignore any leading uppercase letters, "-" and "|".
Fixes: https://rollbar.com/zam/zam/items/25/
=> Fix parsing of Assemblée nationale amendement numbers for commissions

repondeur/tests/fetch/test_fetch_an.py, repondeur/zam_repondeur/fetch/an/amendements.py
When the article has changed since we first created the amendement, we would fail to find it again, then try to insert it again, causing an `IntegrityError` as the unicity constraint in the database fails.
Fixes: https://rollbar.com/zam/zam/items/26/
=> Fix updating amendements from Assemblée nationale if article changes

repondeur/zam_repondeur/models/amendement.py, repondeur/zam_repondeur/views/lectures.py
For some mysterious reason, some lectures cannot be deleted because of circular references between amendements.
This should not happen, and I have not been able to reproduce it yet, but this fix should prevent the error from happening again.
See: http://docs.sqlalchemy.org/en/latest/orm/relationship_api.html#sqlalchemy.orm.relationship.params.post_update
=> Fix circular refs when deleting lecture with sous-amendements

repondeur/zam_repondeur/scripts/worker.py
In the event the consumer was killed while running a task that held a lock, this ensures that all locks are flushed before starting.
https://github.com/coleifer/huey/blob/7092cf07bc3cf7ca794dec31454142b2a6625a9e/huey/consumer.py#L543-L546
=> Make worker flush stale locks on startup

repondeur/db_migrations/versions/4bec591c8da6_fix_inconsistent_spelling_of_apres.py
The parsing of new amendements was fixed in https://github.com/betagouv/zam/pull/137 but this retroactively fixes old values in the DB.
=> Fix inconsistent spelling of "après" in database

.circleci/config.yml, repondeur/pyproject.toml, repondeur/setup.cfg
Installing with pipenv on Circle CI is broken right now because of https://github.com/pypa/pipenv/issues/2956, so let's use a workaround.
=> CI: generate requirements.txt file to install packages

admin/nginx-https.conf.template
Generating a PDF for a lecture with a large number of amendements can take a long time even on a fast server :-/
=> Increase Nginx proxy timeout to 5 minutes for large PDFs

admin/fabfile.py, admin/nginx-https.conf.template, repondeur/docker/Dockerfile.app
The build in the distro is not the latest, but mostly it does not include some Qt patches, causing some issues:
- slow PDF generation
- excessively large file size
- missing footers and table of contents
- impossibility to select text
=> Use an official wkhtmltopdf build

repondeur/tests/test_writer.py, repondeur/zam_repondeur/models/amendement.py, repondeur/zam_repondeur/templates/print.html, repondeur/zam_repondeur/templates/print_macros.html, repondeur/zam_repondeur/writer.py
1. add tests
2. restore sous-amendements after parent ones
3. remove (empty) additional article pages
=> Improve PDFs exports

repondeur/db_migrations/versions/4a3b250d356d_make_article_columns_non_nullable.py, repondeur/tests/models/test_article.py, repondeur/zam_repondeur/models/article.py
In some cases we had `None` values for `mult` or `pos`, causing issues when generating the URL key and getting the item from the DB based on the URL key.
=> Fix broken link to some annexes in PLFSS (Sénat)

repondeur/zam_repondeur/tasks/fetch.py
They may do concurrent writes on the lecture and on articles, causing lock issues.
=> Do not fetch articles and amendements concurrently

.gitignore, repondeur/tests/fetch/test_parse.py, repondeur/zam_repondeur/clean.py, repondeur/zam_repondeur/fetch/an/amendements.py, repondeur/zam_repondeur/fetch/an/liasse_xml.py, repondeur/zam_repondeur/fetch/division.py, repondeur/zam_repondeur/fetch/senat/amendements.py, repondeur/zam_repondeur/models/article.py, repondeur/zam_repondeur/models/division.py, repondeur/zam_repondeur/models/lecture.py
I looked into which tests were slow, and the worst offender was `tests/fetch/test_fetch_senat.py::test_aspire_senat_plf2019_1re_partie` with ~27s on my computer.
I then did some profiling to understand where time was being spent:
The biggest one is `get_one_or_create`, which does a `SELECT` query to the database each time, additionally causing an automatic session flush if we added some objects to the session.
I refactored the fetch logic to avoid doing queries and doing the article/amendement lookup Python-side by iterating on the relationship from the lecture object.
This brings a significant speed improvement:
Most of the time is then spent in the HTML cleaning.
I was able to reduce it a little by using a global `Cleaner` object to avoid paying the initialization cost on each call:
The …
=> Optimize Sénat fetch

repondeur/tests/test_lecture_transfer.py, repondeur/zam_repondeur/templates/transfer_amendements.html
Previously the shared form for both actions cannot be submitted because a field is required only in one case. Now splitted into two distinct forms.
=> Fix custom transfers and required fields

repondeur/requirements.txt, repondeur/setup.py, repondeur/tests/conftest.py, repondeur/zam_repondeur/data.py, repondeur/zam_repondeur/scripts/worker.py, repondeur/zam_repondeur/tasks/periodic.py
This prevents periodic updates by a worker thread from interfering with regular read accesses (e.g. when fetching amendements).
This should fix intermittent `OrganeNotFound` errors observed in production.
=> Add a lock to Redis global data structures

repondeur/zam_repondeur/static/css/zam.css
It looked OK in Firefox but not in Webkit :(
=> Fix email field width in identification form

repondeur/db_migrations/versions/aa4e290e0df2_add_delete_cascades.py, repondeur/zam_repondeur/models/amendement.py, repondeur/zam_repondeur/models/article.py, repondeur/zam_repondeur/models/events/base.py, repondeur/zam_repondeur/models/events/lecture.py, repondeur/zam_repondeur/models/lecture.py, repondeur/zam_repondeur/models/table.py
See:
- https://docs.sqlalchemy.org/en/13/orm/collections.html#using-passive-deletes
- https://docs.sqlalchemy.org/en/13/orm/cascades.html#delete
=> Use database delete cascades (aka "passive deletes") to speed up dossier deactivation

repondeur/tests/fixtures/scraping.py, repondeur/zam_repondeur/fetch/senat/scraping.py
This way, only AN remains in HTTP.
=> Switch all senat.fr scraping URLs to HTTPS
