betagouv/zam

- zam/client/enhancers.py
- zam/client/templates/__init__.py
- zam/client/templates/index.html
From 2.5Mb to 1.2Mb so far by mutualizing articles detail infos.
> Reduce the size of the produced HTML

- aspirateur/MANIFEST.in
- aspirateur/README.md
- aspirateur/requirements-dev.txt
- aspirateur/setup.cfg
- aspirateur/setup.py
- aspirateur/tests/amendements/test_fetch.py
- aspirateur/tests/amendements/test_models.py
- aspirateur/tests/amendements/test_parse.py
- aspirateur/tests/amendements/test_writer.py
- aspirateur/tests/test_clean.py
- aspirateur/tests/test_senateurs.py
- aspirateur/tox.ini
- aspirateur/zam_aspirateur/__main__.py
- aspirateur/zam_aspirateur/amendements/fetch.py
- aspirateur/zam_aspirateur/amendements/models.py
- aspirateur/zam_aspirateur/amendements/parser.py
- aspirateur/zam_aspirateur/amendements/writer.py
- aspirateur/zam_aspirateur/clean.py
- aspirateur/zam_aspirateur/senateurs/fetch.py
- aspirateur/zam_aspirateur/senateurs/parse.py
- visionneuse/zam_visionneuse/models.py
Si la liste complète des amendements n'est pas disponible → erreur.
Si la liste des amendements soumis à la discussion n'est pas disponible → on produire le tableau des amendements dans l'ordre de dépôt, et sans les informations liées à la discussion ("identique", "discussion commune").
> Aspirateur: les amendements peuvent ne pas être encore disponibles

- visionneuse/zam_visionneuse/utils.py
> Fix: forgot to capture stdout in subprocess.run()

- test.sh
- visionneuse/README.md
- visionneuse/requirements-dev.txt
- visionneuse/tests/test_models.py
- visionneuse/zam_visionneuse/__main__.py
- visionneuse/zam_visionneuse/loaders.py
- visionneuse/zam_visionneuse/models.py
- visionneuse/zam_visionneuse/templates/index.html
You need to use the `parse-texte URL > tlfp-output.json` command from https://github.com/regardscitoyens/the-law-factory-parser/pull/77 to generate the output that can be loaded through the visionneuse.
> Load articles content from the output of tlfp

- repondeur/Pipfile
- repondeur/Pipfile.lock
- repondeur/zam_repondeur/__init__.py
- repondeur/zam_repondeur/templates/lecture.html
- repondeur/zam_repondeur/views/reponse.py
> First shot at integrating visionneuse in repondeur

- admin/fabfile.py
- install locale required by tlfp
- add task to view service logs
> Deployment improvements

- aspirateur/requirements.txt
- aspirateur/setup.py
- aspirateur/tests/amendements/test_writer.py
- aspirateur/zam_aspirateur/amendements/writer.py
- repondeur/Pipfile
- repondeur/Pipfile.lock
- repondeur/zam_repondeur/fetch.py
- repondeur/zam_repondeur/templates/reponse_edit.html
- Convert HTML fields to text when exporting to CSV or Excel
- Use consistent vocabulary in CSV/Excel exports and edit form
> Improve CSV & Excel exports 

- repondeur/zam_repondeur/views/reponse.py
Still a WIP, not sure if/where to put tests given the future merge…
> Take care of gouvernemental amendements

- repondeur/zam_repondeur/models/lecture.py
- repondeur/zam_repondeur/templates/lecture.html
- repondeur/zam_repondeur/templates/lectures_list.html
- repondeur/zam_repondeur/views/lectures.py
> Ability to reach the visionneuse from lectures list

- aspirateur/zam_aspirateur/amendements/models.py
- repondeur/tests/test_reponses.py
- repondeur/zam_repondeur/models/lecture.py
- repondeur/zam_repondeur/models/visionneuse.py
- repondeur/zam_repondeur/templates/visionneuse.html
- repondeur/zam_repondeur/views/reponse.py
Makes it easier to regroup amendements/reponses.
Incidentally fixes a lot of bugs!
> Refactor how visionneuse is being built

- repondeur/tests/test_fetch.py
- repondeur/zam_repondeur/fetch.py
As suggested in https://github.com/betagouv/zam/pull/52#discussion_r198630062
> Articles contents refactoring with unit tests

- .circleci/config.yml
- aspirateur/requirements.txt
- aspirateur/tests/amendements/test_fetch_an.py
- repondeur/tests/test_fetch_amendements.py
- repondeur/zam_repondeur/views/lectures.py
I heard some good things about CircleCI so I thought we could give it a try...
> Add CircleCI config

- repondeur/tests/test_reponses.py
- repondeur/zam_repondeur/models/visionneuse.py
> Show amendements introducing additional articles separately

- .circleci/config.yml
https://circleci.com/docs/2.0/collect-test-data/
> Generate test result data for CircleCI

- repondeur/Pipfile
- repondeur/Pipfile.lock
- repondeur/tests/conftest.py
- repondeur/tests/test_articles_add.py
- repondeur/tests/test_lecture_check.py
- repondeur/tests/test_lectures_list.py
- repondeur/tests/test_reponse_edit.py
- repondeur/tests/test_reponses.py
- repondeur/tests/test_reponses_add.py
- repondeur/zam_repondeur/__init__.py
- repondeur/zam_repondeur/models/lecture.py
- repondeur/zam_repondeur/templates/visionneuse.html
- repondeur/zam_repondeur/views/lectures.py
- repondeur/zam_repondeur/views/reponse.py
> Deal with datetimes for lectures and display a warning on update at visionneuse

- CHANGELOG.md
- admin/README.md
- admin/fabfile.py
- admin/index.html.template
- admin/requirements.txt
Still requires styling but better than the previous visionneuse :)
> Basic changelog implementation

- .circleci/config.yml
- admin/fabfile.py
- repondeur/Pipfile
- repondeur/Pipfile.lock
- repondeur/README.md
- repondeur/setup.py
- repondeur/tests/test_download_amendements.py
- repondeur/tests/test_writer.py
- repondeur/zam_repondeur/__init__.py
- repondeur/zam_repondeur/templates/lecture.html
- repondeur/zam_repondeur/templates/print.html
- repondeur/zam_repondeur/views/download.py
- repondeur/zam_repondeur/writer.py
> Generating a pdf/print page with pdfkit

- repondeur/tests/conftest.py
- repondeur/tests/test_lectures_add.py
- repondeur/tests/test_lectures_list.py
- repondeur/tests/test_reponses.py
- repondeur/tests/testapp.py
- repondeur/zam_repondeur/models/lecture.py
- repondeur/zam_repondeur/templates/amendements.html
- repondeur/zam_repondeur/templates/lecture.html
- repondeur/zam_repondeur/templates/lectures_list.html
- repondeur/zam_repondeur/templates/print.html
- repondeur/zam_repondeur/templates/visionneuse.html
- repondeur/zam_repondeur/views/download.py
- repondeur/zam_repondeur/views/lectures.py
- repondeur/zam_repondeur/views/reponse.py
- repondeur/zam_repondeur/writer.py
> Keep the dossier legislatif name for the lecture

- repondeur/setup.cfg
- repondeur/tests/test_amendements.py
- repondeur/tests/test_reponses_add.py
- repondeur/zam_repondeur/__init__.py
- repondeur/zam_repondeur/models/amendement.py
- repondeur/zam_repondeur/templates/amendements.html
- repondeur/zam_repondeur/views/amendement.py
> Ability to bookmark amendements from the list view

- admin/fabfile.py
- admin/requirements.txt
- repondeur/Pipfile
- repondeur/Pipfile.lock
- repondeur/production.ini.template
- repondeur/zam_repondeur/__init__.py
> Add support for reporting production errors to Rollbar

- repondeur/tests/fetch/test_division.py
- repondeur/zam_repondeur/fetch/division.py
See https://rollbar.com/zam/zam/items/4/occurrences/49206590401/
> Deal with more subdiv parsing junk

- repondeur/tests/fetch/test_division.py
- repondeur/zam_repondeur/fetch/division.py
Fixes: https://rollbar.com/zam/zam/items/29/
> Add support for "Section" as the part changed by an amendement

- repondeur/zam_repondeur/templates/amendements.html
> Fix sorting by amendement number

- repondeur/zam_repondeur/templates/lectures_add.html
> Fix keyboard search in lecture select dropdown

- repondeur/tests/conftest.py
- repondeur/tests/fixtures/dossiers.py
- repondeur/tests/models/test_lecture.py
- repondeur/tests/test_lectures_add.py
- repondeur/tests/test_upload_liasse_xml.py
- repondeur/zam_repondeur/models/lecture.py
Like `Sénat, session 2017-2018, Séance publique, Première lecture, texte nº 63`
> Display num lecture in title

- repondeur/zam_repondeur/static/css/zam.css
> Wrap uploaded filename using CSS

- repondeur/tests/test_fetch.py
- repondeur/zam_repondeur/fetch/__init__.py
At least do not raise an error and log.
> Deal with non-existing textes for parsing

- repondeur/zam_repondeur/static/css/visionneuse.css
> Keep notifications on top of any sticky header

- repondeur/zam_repondeur/templates/amendements.html
> Keep box shadow on scroll for sticky table headers

- repondeur/docker/Dockerfile.app
This makes it easier to access the development database.
> Add postgresql-client 10.x tools in webapp container

- repondeur/tests/models/test_article.py
- repondeur/zam_repondeur/models/article.py
https://fr.wikipedia.org/wiki/Association_amicale_des_amateurs_d%27andouillette_authentique
> Fix ordering of articles with interstitial markers ("AAAAA")

- repondeur/zam_repondeur/templates/print.html
Mostly to get it out of my `HEAD` :)
> Minor refactor in PDF export

- repondeur/zam_repondeur/__init__.py
- repondeur/zam_repondeur/scripts/worker.py
- repondeur/zam_repondeur/tasks/fetch.py
- repondeur/zam_repondeur/tasks/periodic.py
Multiple changes conspiring together to avoid the situation where an initial fetch is blocked behind a queue of periodic updates...
> Worker improvements

- repondeur/zam_repondeur/static/css/visionneuse.css
- repondeur/zam_repondeur/templates/_base_visionneuse.html
- repondeur/zam_repondeur/templates/visionneuse.html
> Add a bottom navigation for visionneuse

- repondeur/zam_repondeur/templates/articles_list.html
For reference https://inclusive-components.design/cards/
> Turn the whole article card clickable

- repondeur/tests/test_manual_refresh.py
- repondeur/zam_repondeur/templates/journal.html
- repondeur/zam_repondeur/views/lectures.py
> Explicit message on manual data update

- repondeur/docker/Dockerfile.app
One more step towards removing pipenv 😉
> Install packages using pip requirements in Dockerfile

- repondeur/zam_repondeur/static/smoothscroll/smoothscroll.js
- repondeur/zam_repondeur/templates/_base_visionneuse.html
Using https://github.com/iamdustan/smoothscroll
> Polyfill smoothscrolling for webkit and co

- repondeur/db_migrations/versions/e661a11bf315_remove_intersticial_article_titles_and_.py
- repondeur/tests/models/test_article.py
- repondeur/tests/test_article_edit.py
- repondeur/tests/test_fetch.py
- repondeur/zam_repondeur/fetch/__init__.py
- repondeur/zam_repondeur/models/article.py
- repondeur/zam_repondeur/static/css/visionneuse.css
- repondeur/zam_repondeur/static/css/zam.css
- repondeur/zam_repondeur/templates/amendements.html
- repondeur/zam_repondeur/templates/article_edit.html
- repondeur/zam_repondeur/templates/reponse_edit.html
- repondeur/zam_repondeur/templates/visionneuse.html
- repondeur/zam_repondeur/views/articles.py
- repondeur/zam_repondeur/views/reponse.py
- repondeur/zam_repondeur/views/visionneuse.py
The back button no longer needs the anchor/hash given that we don't want to highlight the line when we are coming back BUT keep the highlight when we save the response.
> Explicit save and back actions on reponse edit + go to next article on jaune edition

- repondeur/db_migrations/versions/704a53402829_add_indexes.py
- repondeur/development-docker.ini
- repondeur/development.ini
- repondeur/zam_repondeur/decorator.py
- repondeur/zam_repondeur/models/amendement.py
- repondeur/zam_repondeur/models/article.py
- repondeur/zam_repondeur/models/lecture.py
- repondeur/zam_repondeur/resources.py
- repondeur/zam_repondeur/templates/_base_visionneuse.html
- repondeur/zam_repondeur/views/articles.py
- repondeur/zam_repondeur/views/download.py
- repondeur/zam_repondeur/views/lectures.py
- repondeur/zam_repondeur/views/reponse.py
- repondeur/zam_repondeur/views/visionneuse.py
Some basic benchmarks on my laptop (actual results may vary):
- lectures list: -38% time
- amendements list: -17% time
- visionneuse: -24% time
- PDF generation: -15% time
- Excel generation: no change
> Performance improvements

- repondeur/zam_repondeur/static/js/notifications.js
> Factorize notifications message

- repondeur/zam_repondeur/templates/_base.html
> Display a confirmation dialog before deletion

- repondeur/zam_repondeur/static/js/notifications.js
Making it not happen upstream will be part of a future PR.
> Do not display notifications if no amendement changed

- repondeur/requirements.txt
- repondeur/tests/sample_data/r1056-a0.html
- repondeur/tests/test_fetch.py
- repondeur/zam_repondeur/fetch/__init__.py
- repondeur/zam_repondeur/fetch/an/dossiers/models.py
Requires https://github.com/regardscitoyens/the-law-factory-parser/issues/103 to be solved though.
> Retrieve annexes content

- repondeur/zam_repondeur/static/css/print.css
- repondeur/zam_repondeur/static/css/visionneuse.css
TinyMCE looks to allow this if you choose paragraph in the dropdown menu for a given cell.
> Deal with paragraphs in tables

- repondeur/tests/fetch/test_division.py
- repondeur/zam_repondeur/fetch/division.py
One day I'll know regular expressions. 'til then I don't know what I'm doing 🤷‍♂️
> Handle subdiv parsing for articles X bis/ter/etc Y

- repondeur/docker/Dockerfile.app
- repondeur/requirements-dev.txt
- repondeur/tests/conftest.py
- repondeur/tests/integration/conftest.py
- repondeur/tests/integration/helpers.py
- repondeur/tests/integration/test_amendements_filtering.py
- repondeur/tests/integration/test_amendements_identiques.py
- repondeur/tests/integration/test_amendements_links.py
- repondeur/tests/integration/test_amendements_sorting.py
- repondeur/tests/integration/test_visionneuse_detail.py
- repondeur/tests/integration/test_visionneuse_home.py
- repondeur/tests/integration/test_visionneuse_search.py
Still requires documentation, to test you must have the geckodriver in your bin folder https://github.com/mozilla/geckodriver/releases
> First iteration on adding tests for JS frontend

- repondeur/tests/test_fetch_amendements.py
- repondeur/zam_repondeur/fetch/an/amendements.py
See https://rollbar.com/zam/zam/items/127/ and https://rollbar.com/zam/zam/items/122/
> Fix a KeyError when the auteur key is not present

- repondeur/zam_repondeur/fetch/an/common.py
Fixes https://rollbar.com/zam/zam/items/152/
> Allow "304 Not Modified" status when fetching remote zip file

- repondeur/zam_repondeur/__init__.py
- repondeur/zam_repondeur/scripts/worker.py
This allows to better identify the origin of SQL queries (for stats and debugging).
> Add application_name param when connecting to Postgres

- repondeur/tests/sample_data/backup_with_articles_old.json
- repondeur/tests/test_backup_add.py
- repondeur/zam_repondeur/views/import_backup.py
Introduced in https://github.com/betagouv/zam/commit/04b69be3903771b7b8aa74459acac08747f5c94e
> Fix: ability to load old backups (articles titles)

- repondeur/tests/fetch/test_division.py
- repondeur/zam_repondeur/fetch/division.py
Make it work with http://www.senat.fr/amendements/2018-2019/255/jeu_complet_2018-2019_255.csv
> Handle sous-sections with dashes and extras

- repondeur/tests/fetch/test_division.py
- repondeur/zam_repondeur/fetch/division.py
> New subdiv parsing case

- repondeur/tests/test_download_amendements.py
- repondeur/zam_repondeur/writer.py
Fixes https://rollbar.com/zam/zam/items/173/ and https://rollbar.com/zam/zam/items/174/
>  Fix broken download of amendements table

- repondeur/tests/test_amendement_edit.py
- repondeur/zam_repondeur/templates/amendement_edit.html
- repondeur/zam_repondeur/views/amendements.py
> Ability to save and transfer an amendement

- repondeur/zam_repondeur/templates/table_detail.html
> Update style of amendement menu

- repondeur/tests/views/test_auth.py
- repondeur/zam_repondeur/static/css/zam2.css
- repondeur/zam_repondeur/templates/login.html
- repondeur/zam_repondeur/templates/welcome.html
- repondeur/zam_repondeur/views/auth.py
It appears that a required field is not enough.
See https://rollbar.com/zam/zam/items/177/ and https://rollbar.com/zam/zam/items/178/
> Deal with auth related errors

- repondeur/zam_repondeur/templates/amendement_edit.html
> Consistent read-only display of the reponse

- CHANGELOG.md
"perspectives" grandit beaucoup, je me demande si c'est pas dommage de faire descendre les nouveautés si bas.. z'en dites quoi?
> update démo et calendrier des prod

- repondeur/zam_repondeur/clean.py
Bleach uses html5lib, which is not thread-safe, so we have to use a cleaner instance per thread instead of a global one to avoid transient errors in our workers.
See: https://github.com/mozilla/bleach/issues/370
Fixes: https://rollbar.com/zam/zam/items/202/
> Use thread-local Bleach cleaners

- repondeur/zam_repondeur/clean.py
Fixes: https://rollbar.com/zam/zam/items/203/
Fixes: https://rollbar.com/zam/zam/items/204/
> Better thread-local fix?

- repondeur/requirements.txt
- repondeur/setup.py
- repondeur/tests/fetch/test_division.py
- repondeur/zam_repondeur/fetch/division.py
- repondeur/zam_repondeur/models/article.py
- repondeur/zam_repondeur/models/division.py
The new implementation uses the parsy library to allow some modularity and easier maintenance than a big regex...
https://parsy.readthedocs.io/en/latest/overview.html
Fixes: https://rollbar.com/zam/zam/items/169/
> New parser for divisions (article, chapitre, ...)

- repondeur/tests/test_amendements.py
- repondeur/zam_repondeur/static/css/zam.css
- repondeur/zam_repondeur/templates/amendements.html
- repondeur/zam_repondeur/templates/table_detail.html
Maybe a macro would be more pertinent?
> Deal with abbreviated Gouv/Irr/Ret statuses

- repondeur/tests/fetch/test_division.py
- repondeur/zam_repondeur/fetch/an/amendements.py
- repondeur/zam_repondeur/fetch/an/liasse_xml.py
- repondeur/zam_repondeur/fetch/division.py
- repondeur/zam_repondeur/fetch/senat/amendements.py
Fixes https://rollbar.com/zam/zam/items/209/
> Add support for subdiv being the Texte's long title

- repondeur/tests/fetch/test_division.py
- repondeur/zam_repondeur/fetch/division.py
Fixes https://rollbar.com/zam/zam/items/251/
>  Add support for additional articles before the title

- repondeur/tests/fetch/test_division.py
- repondeur/zam_repondeur/fetch/division.py
Fixes https://rollbar.com/zam/zam/items/302/
> Add support for additional articles before a chapitre

- repondeur/tests/fetch/test_organes_acteurs.py
- repondeur/tests/models/test_lecture.py
- repondeur/zam_repondeur/models/lecture.py
Otherwise it can be badly truncated
See https://zam.framaboard.org/?controller=TaskViewController&action=show&task_id=295&project_id=1
> Rely on full libelle for organe

- repondeur/tests/fetch/test_fetch_an.py
- repondeur/tests/fetch/test_update_an.py
- repondeur/zam_repondeur/models/__init__.py
> Revert "Remove useless begin_nested() in get_one_or_create"

- repondeur/tests/sample_data/pjl17-701.html
- repondeur/tests/test_fetch_articles.py
- repondeur/zam_repondeur/fetch/articles.py
For instance in https://www.senat.fr/leg/pjl17-701.html
> Do not create an article if no titre in data

- repondeur/tests/test_lecture_transfer.py
- repondeur/zam_repondeur/models/amendement.py
Otherwise if someone is invited but has no name yet, it displays an empty/blank string in the Index.
> Fallback on user email for table name

- repondeur/zam_repondeur/templates/lecture_options.html
Follow up on https://github.com/betagouv/zam/pull/642
> Minor typos in wording

- repondeur/zam_repondeur/__init__.py
- repondeur/zam_repondeur/auth.py
- repondeur/zam_repondeur/monitoring.py
* DB connexion
* Redis connexion + keys count
* Huey queue count
> Basic monitoring view

- repondeur/tests/views/test_auth.py
- repondeur/zam_repondeur/templates/_base.html
Follow up on https://github.com/betagouv/zam/pull/682
> Allow admins to edit their user names

- repondeur/tests/views/test_shared_tables.py
- repondeur/zam_repondeur/resources.py
See https://rollbar.com/zam/zam/items/338/ + https://rollbar.com/zam/zam/items/339/
The filter was not applied on the lecture.
> Fix error when editing a shared table not unique

- repondeur/zam_repondeur/models/__init__.py
in get_one_or_create
Reverts https://github.com/betagouv/zam/commit/40346813c6ca9164d8ece20b7e8ed57ee0b2d07f
> Manual retry in case of IntegrityError
